Dev/profile page
thor2304/HapticEngines pull request #17
Opened 2023-10-27 21:10 UTC by Queztex

closes #5

2023-10-28 09:30 UTC, thor2304 requested changes
Not entirely ready.

2023-10-28 09:30 UTC, thor2304 commented on screens/ProfileScreen.tsx
> +    const userID = 2;
This is a problem. 
You should expect the id to come through the Route param as described by ProfileProps

2023-10-28 09:30 UTC, thor2304 commented on screens/ProfileScreen.tsx
> +    // TODO: Add functionality to allow users to edit their information.
A TODO comment about not being done when merging to master?

2023-10-28 09:30 UTC, thor2304 commented on screens/ProfileScreen.tsx
> +        color: '#BFBFBF'
This is a problem. Use the ThemeContext instead.

2023-10-28 09:30 UTC, thor2304 commented on screens/ProfileScreen.tsx
> +        color: '#BFBFBF'
Even better define the style in the StyleSheet class like the DiscoveryPage/CarCard does

2023-10-28 09:30 UTC, thor2304 commented on screens/ProfileScreen.tsx
> +    const userID = 2;
Talk to Tobias about how to get the userId added when doing navigation fromt he TabNavigator.
Otherwise find a way to make it "loaded" from somewhere, so it is not hardcoded like that. 
Make it seem a bit more believable.

2023-10-28 11:11 UTC, thor2304 commented
See the updated change for the background card on the profile page:
https://www.figma.com/file/tcw9PtUFw7v4RtZzoWUjnB/HapticEngines?type=design&node-id=0-1&mode=design&t=zJxFOrnhYd7980vv-0

(This is to ensure readability between the contrast color and the text color)

2023-10-28 11:38 UTC, KevinTorp commented
@Queztex  Add the CHANGE THEME button to the profile page

(can use the one which was there before changing the page - just design it so it matches the rest of the designs)

2023-10-30 14:38 UTC, TobiasBak approved these changes

2023-10-30 15:09 UTC, merged