Notifications into Master
thor2304/HapticEngines pull request #24
Opened 2023-10-29 15:22 UTC by Rachristi

**OBS**
promt with login might occure, this is for the EAS(expo application services), which allows for push notifications through firebase APIcall 
Credentials
Login: rachristi@outlook.dk
pass: 1234QWER

2023-10-29 15:36 UTC, thor2304 requested changes
I think there are a few things to clean up a little bit. 
(i did a speedrun review, so forgive me if any of the comments seem stupid or rushed, for they were)

2023-10-29 15:36 UTC, thor2304 commented on .vscode/launch.json
This should not be on git

2023-10-29 15:36 UTC, thor2304 commented on app.json
> +    "slug": "thetravellingcarsalesman",
why this changed?

2023-10-29 15:36 UTC, thor2304 commented on services/BackendHandler.tsx
This is bad. it should not be a .tsx file it should remain .ts

2023-10-29 15:36 UTC, thor2304 commented on services/notifications/BackgroundTask.tsx
> +export default function BackgroundFetchScreen() {
I think this screen should be extracted to a component. That uses the rest of the service defined in this script. (Take everything from this point down

2023-10-29 15:36 UTC, thor2304 commented on services/notifications/usePushNotifications.ts
> +                lightColor: '#FF231F7C',
I spy with my little eye, a rogue color that does not come from a theme

2023-10-29 15:36 UTC, thor2304 commented on services/notifications/usePushNotifications.ts
> +                projectId: Constants.expoConfig?.extra?.eas.projectId,
Uf, this does not look nice. If you are 100% certain that these variables will always be populated please write a short comment why. If not. Check them and do something else to avoid the `?.` syntax

2023-10-29 15:36 UTC, thor2304 commented on .vscode/launch.json
Uncommit it, then add `.vscode` to `.gitignore`

2023-10-29 15:37 UTC, Rachristi commented on services/notifications/usePushNotifications.ts
> +                lightColor: '#FF231F7C',
These are subject to change. Needs to implemented with profile.
Nice spot! :D

2023-10-29 15:38 UTC, Rachristi commented on app.json
> +    "slug": "thetravellingcarsalesman",
This is change to fit the format of EAS and Firebase

2023-10-29 15:41 UTC, Rachristi commented on services/BackendHandler.tsx
I believe this acually originated from your commit when you helped on the changes for BackendHandler. Ill revert it

2023-10-29 15:43 UTC, Rachristi commented on app.json
> +    "slug": "thetravellingcarsalesman",
> This is change to fit the format of EAS and Firebase 

I take this back

2023-10-29 15:48 UTC, Rachristi commented on services/notifications/BackgroundTask.tsx
> +export default function BackgroundFetchScreen() {
Unsure what benefit this is. 
Its closely related to the rest of the files.

2023-10-29 16:02 UTC, Rachristi commented on services/notifications/usePushNotifications.ts
> +                projectId: Constants.expoConfig?.extra?.eas.projectId,
Expo constants is information that remains constant. 
Project id is pulled from App.JSON "expo"
and should always be precent as we are using expo libraries.

2023-10-29 18:46 UTC, thor2304 commented on services/BackendHandler.tsx
I would also think it was from my commit, so no hard feelings

2023-10-29 18:48 UTC, thor2304 commented on services/notifications/BackgroundTask.tsx
> +export default function BackgroundFetchScreen() {
Splitting service functionality from React component functionality.
Essentially the majority of the file is tasked with making notifications and BackgroundTasks to work. This last function is purely React stuff for displaying something on the frontend.
The responsibilities, and purposes are quite different and therefore display should preferably be separated from functionality

2023-10-29 18:50 UTC, thor2304 commented on services/notifications/usePushNotifications.ts
> +                projectId: Constants.expoConfig?.extra?.eas.projectId,
Ahh i see, i think it would be great to add it as a source code in the comment that this is read from the app.json file that is bundled with the project and as such it will always be present.

2023-10-29 18:53 UTC, thor2304 commented on services/notifications/BackgroundTask.tsx
> +}
This entire stretch is improperly indented. Man it hurts 😄

2023-10-30 15:01 UTC, thor2304 commented on services/BackendHandler.ts
> -        // return "heheheh"
pls fix

2023-10-30 15:02 UTC, thor2304 approved these changes

2023-10-30 15:02 UTC, merged